smtp:
  port: 1025
http:
  port: 8025
#  path: box
#  allow_origins: "http://localhost:5173"
#  assets_root: "./public"
storage:
  use: directory
  per_room_limit: 100
  directory:
    path: ""
#storage:
#  use: mongodb
#  per_room_limit: 1000
#  mongodb:
#    connection: mongodb
#    collection: emails
authentication:
  use: file
  file:
    path: ".mh-authfile"
#authentication:
#  use: mongodb
#  mongodb:
#    connection: mongodb
#    collection: users
#ui:
#  file: ui.json
#db:
#  connections:
#    mongodb:
#      uri: 127.0.0.1:27017
#      db_name: mailhedgehog
#      db_user: test
#      db_pass: testpass

